[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

[dependencies]
forge-std = "1.8.2"
openzeppelin-contracts = "5.0.2"
eigenlayer-contracts = { git = "https://github.com/Layr-Labs/eigenlayer-contracts.git", branch = "mainnet" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RRP_URL}"
mainnet = "${MAINNET_RPC_URL}"